- include/open62541pp/Node.h
- include/open62541pp/TypeConverter.h
- include/open62541pp/types/Variant.h
- tests/Types.cpp
Addressing feature request #18.
Added new static methods `Variant::fromScalar`, `Variant::fromArray` to create variants the most efficient way (avoid copys).
> feat: create variant from scalar/array

- CHANGELOG.md
- examples/server.cpp
- examples/server_instantiation.cpp
- include/open62541pp/Node.h
- include/open62541pp/services/Attribute.h
- src/services/Attribute.cpp
- tests/Services.cpp
Pass `LocalizedText` instead of members (`locale`, `text`) to `Node::writeDisplayName`, `Node::writeDescription`, `services::writeDisplayName`, `services::writeDescription`.
As discussed in #27.
> feat: use LocalizedText as argument instead of members

- .github/workflows/open62541-compatibility.yml
- .github/workflows/package.yml
- cmake/open62541ppConfig.cmake.in
- examples/CMakeLists.txt
Add CI workflow to test CMake package (install target and config file) as discussed in #41.
The existing examples are used for testing. They can be built stand-alone with an external open62541pp installation. If everything works fine, the examples should compile without errors. Running those examples should not be necessary.
> ci: test cmake package

- examples/client_minimal.cpp
- examples/client_subscription.cpp
- include/open62541pp/Client.h
- include/open62541pp/ErrorHandling.h
- src/Client.cpp
- src/ClientContext.h
- src/MonitoredItem.cpp
- src/Subscription.cpp
- src/types/Builtin.cpp
- src/version.h
- tests/Client.cpp
Register client state callbacks:
- `Client::onConnected`
- `Client::onDisconnected`
- `Client::onSessionActivated`
- `Client::onSessionClosed`
This is especially useful to recreate subscriptions and monitored items after the connection to the server was lost and the client has to reconnect (see updated `client_subscription` example).
> feat: client state callbacks

- examples/CMakeLists.txt
- examples/server_valuecallback.cpp
- include/open62541pp/Server.h
- include/open62541pp/ValueBackend.h
- include/open62541pp/open62541pp.h
- src/Server.cpp
- src/ServerContext.h
- src/services/NodeManagement.cpp
- tests/Server.cpp
As requested in #62.
- `Server::setVariableNodeValueCallback` method
- Add example `server_valuecallback`
Open questions:
- Provide `NodeId` in callback functions?
> feat: add variable node value callbacks

- README.md
Fix cmake code in the main readme which does not compile as is.
> chore: fix cmake code in readme

- include/open62541pp/Node.h
- include/open62541pp/services/NodeManagement.h
- include/open62541pp/types/Composed.h
- src/services/NodeManagement.cpp
- src/types/Composed.cpp
- tests/Services.cpp
Add missing node management functions:
- `Node::addReferenceType` / `services::addReferenceType`
- `Node::addDataType` / `services::addDataType`
- `Node::addView` / `services::addView`
Add missing node attributes wrapper:
- `ReferenceTypeAttributes`
- `DataTypeAttributes`
- `ViewAttributes`
> feat: addReferenceType, addDataType, addView

- include/open62541pp/TypeConverter.h
- include/open62541pp/TypeWrapper.h
- include/open62541pp/types/Variant.h
- src/types/Variant.cpp
- tests/Types.cpp
New methods:
- `Variant::getDataType`
- `Variant::getScalar` without template type (returns `void*`)
- `Variant::getArray` without template type (returns `void*`)
- `Variant::setScalar` overload with custom `UA_DataType`
- `Variant::setScalarCopy` overload with custom `UA_DataType`
- `Variant::setArray` overload with custom `UA_DataType`
- `Variant::setArrayCopy` overload with custom `UA_DataType`
> feat: variant methods for custom types

- include/open62541pp/ErrorHandling.h
- include/open62541pp/ValueBackend.h
- include/open62541pp/types/Builtin.h
- include/open62541pp/types/Composed.h
- include/open62541pp/types/DataValue.h
- src/types/DataValue.cpp
- tests/Server.cpp
- tests/Services.cpp
- tests/Types.cpp
Simple wrapper of `UA_StatusCode`.
`StatusCode` can be used interchangeably with `UA_StatusCode` due to implicit conversions (without any overhead) but provides some methods to simplify the handling with status codes.
Methods:
- `StatusCode::name`
- `StatusCode::isGood`
- `StatusCode::isUncertain`
- `StatusCode::isBad`
- `StatusCode::throwIfBad`
> feat: StatusCode class

- include/open62541pp/Node.h
- tests/Node.cpp
**Goal**: Reduce the memory size of Node. Node has two members: a `NodeId` (24 byte) and a `Server`/`Client` instance (> 16 byte). `Server`/`Client`s only member is a `shared_ptr`. Depending on the the implementation, the memory overhead of a `shared_ptr` compared to a plain reference in > 8 byte.
The only downside is, that the lifetime of the server or client won't be extended by a node instance.
@duca, we have been talking about this and (after some thinking), I totally agree. Thanks for your patience :)
> refactor: store Server/Client instance in Node as reference

- include/open62541pp/DataTypeBuilder.h
- include/open62541pp/Node.h
- include/open62541pp/TypeConverter.h
- include/open62541pp/types/Composed.h
- include/open62541pp/types/ExtensionObject.h
- include/open62541pp/types/Variant.h
- tests/TypeConverter.cpp
- tests/Types.cpp
Remove `type`/`typeIndex` template parameters with `guessType<T>()`/`guessTypeIndex<T>()` as default.
Instead, the data type is inferred in the function body.
Ambiguous types have to be specified in overloaded methods with UA_DataType parameter, e.g.:
```cpp
opcua::Variant var;
UA_String str;  // ambiguous type due to UA_ByteString and UA_XmlElement type aliases
// previously
var.setScalar<UA_String, opcua.:Types::String>(str);
// now
var.setScalar(str, UA_TYPES[UA_TYPES_STRING]);
```
> refactor!: remove type/typeIndex template parameters

- examples/server.cpp
- examples/server_datasource.cpp
- examples/server_valuecallback.cpp
- include/open62541pp/Node.h
- include/open62541pp/services/Attribute.h
- include/open62541pp/types/Composed.h
- include/open62541pp/types/NodeId.h
- tests/Node.cpp
- tests/Types.cpp
As discussed in #59.
Provide overloads to deduce the data type id of `Variable` or `VariableType` nodes from the template type `T`:
- `Node::writeDataType<T>()`
- `VariableAttributes::setDataType<T>()`
- `VariableTypeAttributes::setDataType<T>()`
> feat: deduce data type from template type

- include/open62541pp/types/NodeId.h
- tests/Types.cpp
> feat: `std::hash` specialization for `NodeId` and `ExpandedNodeId`

- examples/custom_datatypes/client_custom_datatypes.cpp
- include/open62541pp/Node.h
- include/open62541pp/services/Attribute.h
- src/Client.cpp
- src/Server.cpp
- tests/Server.cpp
- tests/Services.cpp
New overloads:
- `DataValue readDataValue(T& serverOrClient, const NodeId& id)`
- `Variant readValue(T& serverOrClient, const NodeId& id)`
- `DataValue Node::readDataValue()`
- `Variant Node::readValue()`
**Deprecate** original function signature. No performance benefit to pass `Variant`/`DataValue` by reference. The original functions will be removed in the future for the sake of simplicity.
> feat: add overloads to return `Variant`/`DataValue` by value from read functions

- README.md
- examples/client_connect.cpp
- examples/client_minimal.cpp
- examples/server.cpp
- examples/server_instantiation.cpp
- examples/server_minimal.cpp
- examples/server_valuecallback.cpp
- include/open62541pp/Node.h
- tests/Node.cpp
- tests/Server.cpp
More specific naming of the `Node` methods to read/write scalar/array values.
The prefix should always be the same, e.g. `Node::writeValue` and the `Node::writeValueScalar` instead of `Node::writeScalar`. It's not clear, that the `Value` attribute of the node is written.
Add methods:
- `Node::readValueScalar`
- `Node::readValueArray`
- `Node::writeValueScalar`
- `Node::writeValueArray`
Deprecate methods:
- `Node::readScalar`
- `Node::readArray`
- `Node::writeScalar`
- `Node::writeArray`
> feat: specific naming of Node methods to read/write scalar/array values

- README.md
- examples/client_method.cpp
- examples/server_instantiation.cpp
- examples/server_method.cpp
- include/open62541pp/TypeConverter.h
- tests/TypeConverter.cpp
Add template specializations for `TypeConverter` to allow following string conversions:
- `TypeConverter<std::string_view>`: convert to and from native `UA_String`
- `TypeConverter<const char*>`: convert to native `UA_String`
- `TypeConverter<char[N]>`: convert to native `UA_String`
> feat: conversions from `string_view`, `const char*`, `char[N]` to `UA_String`

- include/open62541pp/Node.h
- src/Client.cpp
- src/Node.cpp
- src/Server.cpp
- tests/Node.cpp
Closes #88.
Initial ideas was to add following methods:
- `bool NodeId::exists(Server&)`
- `bool NodeId::exists(Client&)`
This would introduce client and server logic to the `NodeId` data type, which is by definition agnostic to the actual server-client-connection. Instead, the `Node` class seems to be a better place, because it couples `Server`/`Client` and the actual `NodeId`.
Following changes are proposed:
- Remove the optional existance check in the `Node` constructor with the `checkExists` flag
- Add a method `Node::exists` to explicitly check the existance of a node
If just the existance of a `NodeId` should be checked, a `Node` object must be created. BUT the construction is very cheap.
@johanneskopf: Any remarks/ideas?
> feat!: check if node id exists

- include/open62541pp/types/Builtin.h
- src/types/Builtin.cpp
Workaround to allow GCC 7 with partial C++ 17 support: https://en.cppreference.com/w/cpp/compiler_support/17
Use `<experimental/filesystem>` instead of `<filesystem>`.
> build: gcc 7 support

- include/open62541pp/services/View.h
- include/open62541pp/types/Composed.h
- src/services/View.cpp
- src/types/Composed.cpp
- tests/Services.cpp
- tests/Types.cpp
Expose raw view services (client only):
- `services::browse`
- `services::browseNext`
- `services::translateBrowsePathsToNodeIds`
- `services::registerNodes`
- `services::unregisterNodes`
> feat: raw view services

- include/open62541pp/TypeConverter.h
- include/open62541pp/types/Variant.h
Improve `Variant::setScalarCopy` and `Variant::setArrayCopy` performance for native and wrapper types.
> perf: variant setter for natives and wrappers

- CHANGELOG.md
- include/open62541pp/types/Variant.h
- tests/Types.cpp
Check variant type by template type, e.g. `variant.isType<int>()`.
> feat: templated Variant::isType overload

- include/open62541pp/DataTypeBuilder.h
- include/open62541pp/Node.h
- include/open62541pp/TypeRegistry.h
- include/open62541pp/detail/helper.h
- include/open62541pp/types/Composed.h
- include/open62541pp/types/ExtensionObject.h
- include/open62541pp/types/NodeId.h
- include/open62541pp/types/Variant.h
- src/types/Composed.cpp
- src/types/Variant.cpp
- tests/TypeRegistry.cpp
- tests/helper.cpp
Retrieve the data type (`UA_DataType`) by the provided template type.
Types must be registered with `TypeRegistry` specializations.
Example:
```cpp
auto& dt = opcua::getDataType<int32_t>();
assert(&dt == &UA_TYPES[UA_TYPES_INT32]);
```
> feat: expose getDataType

- include/open62541pp/Client.h
- src/Client.cpp
- tests/Client.cpp
Allows constructing the Client directly with a custom logger. 
See #149  and #150
> feat: add logger to constructor of Client

- .clang-format
- examples/custom_datatypes/client_custom_datatypes.cpp
- include/open62541pp/Node.h
- include/open62541pp/TypeConverter.h
- include/open62541pp/services/Attribute.h
- include/open62541pp/types/NodeId.h
- include/open62541pp/types/Variant.h
- src/types/NodeId.cpp
- tests/Node.cpp
- tests/Types.cpp
The `Type` enum can easily replaced with the `DataTypeId` enum or templated checks:
`Variant::isType(Type)` -> `Variant::isType<T>()` or `Variant::isType(DataTypeId)`
Originally, `Type` was intended to represent the current data type of a `Variant`. But open62541 allows to store any data types, not only the standard variant types as defined in the OPC UA standard: https://www.open62541.org/doc/1.3/types.html#variant
> feat!: deprecate Type enum

- include/open62541pp/Node.h
- include/open62541pp/services/Attribute.h
Remove functions that have been deprecated 6 months ago:
- `Node::readDataValue(DataValue&)`, use `Node::readDataValue()` instead
- `Node::readValue(DataValue&)`, use `Node::readValue()` instead
- `Node::readScalar<T>()`, use `Node::readValueScalar<T>()` instead
- `Node::readArray<T>()`, use `Node::readValueArray<T>()` instead
- `services::readDataValue(T&, const NodeId&, DataValue&)`, use `services::readDataValue(T&, const NodeId&)` instead
- `services::readValue(T&, const NodeId&, Variant&)`, use `services::readValue(T&, const NodeId&)` instead
> feat!: remove deprecated functions to read/write attributes

- include/open62541pp/types/Variant.h
- tests/Types.cpp
This PR fixes some problems that can be observed, when using one of the following overloads with `std::vector<bool>` due to its specialization.
1. `void setArrayCopy(ArrayLike&& array)`
2. `void setArrayCopy(ArrayLike&& array, const UA_DataType& dataType)`
3. `void setArrayCopy(InputIt first, InputIt last)`
4. `void setArrayCopy(InputIt first, InputIt last, const UA_DataType& dataType)`
See #164 for details.
> fix: Variant::setArrayCopy

- include/open62541pp/types/Variant.h
- tests/Types.cpp
Ref-qualified scalar getters getScalar allow to move the scalar out of a temporary Variant.
```cpp
String str = Variant::fromScalar("test").getScalar<String>();  // no copy, NEW!
```
> perf: ref-qualified Variant::getScalar

- include/open62541pp/types/DataValue.h
- tests/Types.cpp
Use same naming as in OPC UA standard.
- `DataValue::hasStatusCode` -> `DataValue::hasStatus`
- `DataValue::getStatusCode` -> `DataValue::getStatus`
- `DataValue::setStatusCode` -> `DataValue::setStatus`
The old methods are deprecated and will be removed in the future.
> feat: rename DataValue methods from has/get/setStatusCode to has/get/setStatus

- src/Client.cpp
- src/services/Method.cpp
Arrays should be deallocated using UA_Array_delete.
Otherwise non trivial members are not deleted and empty arrays cause problems. 
See #180
> fix: use UA_Array_delete instead of UA_free

- include/open62541pp/Node.h
- include/open62541pp/detail/traits.h
- include/open62541pp/types/DataValue.h
- include/open62541pp/types/Variant.h
- src/Event.cpp
- tests/CMakeLists.txt
- tests/Services.cpp
- tests/Types.cpp
- tests/traits.cpp
| Removed overload                            | Replacement                                     |
|---------------------------------------------|-------------------------------------------------|
| `setArray(Span<T>)`                         | `setArray(ArrayLike&&)`                         |
| `setArray(Span<T>, const UA_DataType&)`     | `setArray(ArrayLike&&, const UA_DataType&)`     |
| `setArrayCopy(Span<T>)`                     | `setArrayCopy(ArrayLike&&)`                     |
| `setArrayCopy(Span<T>, const UA_DataType&)` | `setArrayCopy(ArrayLike&&, const UA_DataType&)` |
| `fromScalar(T&)`                            | `fromScalar(T&&)`                               |
| `fromScalar(T&, const UA_DataType&)`        | `fromScalar(T&&, const UA_DataType&)`           |
| …
> feat: simplify Variant methods, use VariantPolicy for factory methods

- examples/client_subscription.cpp
- include/open62541pp/MonitoredItem.h
- include/open62541pp/Subscription.h
- include/open62541pp/services/MonitoredItem.h
- src/MonitoredItem.cpp
- src/Subscription.cpp
- src/services/MonitoredItem.cpp
- tests/Services.cpp
- tests/Subscription_MonitoredItem.cpp
The custom struct `MonitoringParameters` shadows the OPC UA type [`MonitoringParameter`](https://reference.opcfoundation.org/Core/Part4/v104/docs/7.16).
Alias for backwards compatibility added but deprecated.
Closes #186 .
> feat!: rename `MonitoringParameters` -> `MonitoringParametersEx`

- include/open62541pp/DataType.h
- src/DataType.cpp
- tests/DataType.cpp
Deep comparison of all `UA_DataType` fields should not be required. Just compare the `typeId` instead.
> fix: compare DataType only by typeId

- doc/examples.dox
- examples/CMakeLists.txt
- examples/server.cpp
- examples/server_logger.cpp
- include/open62541pp/Logger.h
- tools/run_examples.py
Remove following logger utility functions:
```cpp
constexpr std::string_view getLogLevelName(opcua::LogLevel level);
constexpr std::string_view getLogCategoryName(opcua::LogCategory category);
```
Add `server_logger` example with previous utility functions.
> feat!: remove logger utility functions, add server_logger example

- include/open62541pp/AccessControl.h
- src/AccessControl.cpp
- src/CustomAccessControl.cpp
- tests/AccessControl.cpp
Following function signature of `AccessControlBase` is changed:
```cpp
// old
virtual std::vector<UserTokenPolicy> getUserTokenPolicies() = 0;
// new
virtual Span<UserTokenPolicy> getUserTokenPolicies() = 0;
```
The user token policies can be stored internally as a `std::vector<UserTokenPolicy>` and returned as a `Span<UserTokenPolicy>`.
Please make sure, that the span must be valid throughout the lifetime of the AccessControl instance. Modifications of the underlying vector may invalidate the span.
> feat!: return AccessControl user token policies as Span

- .github/workflows/ci.yml
See https://github.com/actions/runner-images/issues/9491.
The issue should be fixed in the next runner image for Ubuntu 22.04: https://github.com/actions/runner-images/pull/9513
> ci: temporary workaround for sanitizer crashes

- include/open62541pp/detail/ContextMap.h
- include/open62541pp/services/detail/MonitoredItemContext.h
- src/Subscription.cpp
- src/services/MonitoredItem.cpp
- tests/Services.cpp
Simplify handling of immediate callbacks before context insertion.
> refactor: handle immediate data change callbacks

- include/open62541pp/MonitoredItem.h
- include/open62541pp/Subscription.h
- include/open62541pp/services/MonitoredItem.h
- src/MonitoredItem.cpp
- src/Subscription.cpp
- src/services/MonitoredItem.cpp
- tests/Subscription_MonitoredItem.cpp
Symmetric implementation (same definition for `Server` and `Client`) for:
- `services::createMonitoredItemDataChange`
- `services::deleteMonitoredItem`
> feat: symmetric createMonitoredItemDataChange, deleteMonitoredItem

- examples/client_subscription.cpp
- examples/events/client_eventfilter.cpp
- include/open62541pp/Subscription.h
- src/Subscription.cpp
- tests/Subscription_MonitoredItem.cpp
Solves lifetime issues as discussed in #187.
Use the same callback signature as in the `services` namespace. If the user wants to access the `MonitoredItem` object, it can be easily created by capturing the server/client instance (the user has to decide about the lifetime!).
```cpp
auto sub = client.createSubscription();
auto mon = sub.subscribeDataChange(
opcua::VariableId::Server_ServerStatus_CurrentTime,  // monitored node id
opcua::AttributeId::Value,  // monitored attribute
[&](const opcua::MonitoredItem<Client>& item, const opcua::DataValue& value) {
// ...
}
);
```
```cpp
auto sub = client.createSubscription();
auto mon = sub.subscribeDataChange(
opcua::VariableId::Server_ServerStatus_CurrentTime,  // monitored node id
opcua::AttributeId::Value,  // monitored attribute
[&](uint32_t …
```
> feat!: deprecate high-level `DataChangeCallback` and `EventCallback`

- include/open62541pp/DataTypeBuilder.h
- include/open62541pp/TypeWrapper.h
- include/open62541pp/types/Builtin.h
- include/open62541pp/types/Composed.h
- include/open62541pp/types/DataValue.h
- include/open62541pp/types/DateTime.h
- include/open62541pp/types/ExtensionObject.h
- include/open62541pp/types/NodeId.h
- include/open62541pp/types/Variant.h
- src/types/Builtin.cpp
`TypeWrapper<T, typeIndex>::TypeWrapperBase` alias is useless. Just use `TypeWrapper` instead.
> refactor!: deprecate TypeWrapperBase alias, use TypeWrapper instead

- include/open62541pp/Result.h
- tests/ClientService.cpp
- tests/Result.cpp
The implicit conversions were a compatibility feature to not break existing code. But they cause more confusion in my opinion, so let's mark this as a breaking change for the next release.
All functions in the `services` namespace will adopt the `Result<T>` type as a return type - both sync and async versions.
> feat!: remove implicit conversions from `Result<T>` to `T`

- examples/client_subscription.cpp
- examples/custom_datatypes/server_custom_datatypes.cpp
- examples/events/client_eventfilter.cpp
- examples/method/client_method.cpp
- examples/method/client_method_async.cpp
- examples/server_datasource.cpp
- examples/server_instantiation.cpp
- include/open62541pp/Event.h
- include/open62541pp/MonitoredItem.h
- include/open62541pp/Node.h
- include/open62541pp/Session.h
- include/open62541pp/Subscription.h
- src/Event.cpp
- src/MonitoredItem.cpp
- src/Node.cpp
- src/Session.cpp
- tests/Event.cpp
- tests/Node.cpp
- tests/Server.cpp
- tests/Subscription_MonitoredItem.cpp
Strip `get` prefix of simple getter member functions:
- `Node::getConnection()` -> `Node::connection()`
- `Node::getNodeId()` -> `Node::id()`
- `Session::getConnection()` -> `Session::connection()`
- `Session::getSessionId()` -> `Session::id()`
- `Subscription::getConnection()` -> `Subscription::connection()`
- `Subscription::getSubscriptionId()` -> `Subscription::subscriptionId()`
- `MonitoredItem::getConnection()` -> `MonitoredItem::connection()`
- `MonitoredItem::getSubscriptionId()` -> `MonitoredItem::getSubscriptionId()`
- `MonitoredItem::getMonitoredItemId()` -> `MonitoredItem::monitoredItemId()`
- `Event::getConnection()` -> `Event::connection()`
- `Event::getNodeId()` -> `Event::id()`
Old member function names are deprecated and will be removed in the future.
As discusses in #197.
> refactor!: strip get prefix of simple getters

- include/open62541pp/Client.h
- include/open62541pp/Event.h
- include/open62541pp/MonitoredItem.h
- include/open62541pp/Node.h
- include/open62541pp/Server.h
- include/open62541pp/Session.h
- include/open62541pp/Subscription.h
- include/open62541pp/services/Attribute.h
- include/open62541pp/services/Attribute_highlevel.h
- include/open62541pp/services/Method.h
- include/open62541pp/services/MonitoredItem.h
- include/open62541pp/services/NodeManagement.h
- include/open62541pp/services/Subscription.h
- src/Event.cpp
- src/services/Attribute.cpp
- src/services/Method.cpp
- src/services/NodeManagement.cpp
- src/services/Subscription.cpp
- tests/Logger.cpp
- tests/Node.cpp
- tests/Services.cpp
- tools/gen_attribute_highlevel.py
Mainly to copy/reuse parameter descriptions for the documentation.
> refactor: rename ServerOrClient -> Connection

- include/open62541pp/types/Variant.h
> fix: Variant::isArray check

- .github/workflows/ci.yml
GCC 13 was removed from Ubuntu 22.04 image: https://github.com/actions/runner-images/issues/9866
> ci: fix gcc 13

- .github/workflows/ci.yml
- .github/workflows/doc.yml
- .github/workflows/examples.yml
- .github/workflows/open62541-compatibility.yml
- .github/workflows/package.yml
- Add new available compilers to CI workflow: Clang 16, 17, 18
> ci: use ubuntu 24.04 image and new available compilers

- src/Server.cpp
Avoid multiple calls to `applyDefaults` from different translation units where the session registry is applied. Instead only apply the session registry after the server config is created or the access control set.
Closes #285.
> fix: stack overflow in session registry when running from different translation units

- include/open62541pp/Bitmask.h
- tests/Bitmask.cpp
```cpp
// allow bitwise operations
// 1. with template specialization of IsBitmaskEnum trait
template <>
struct IsBitmaskEnum<Access> : std::true_type {};
// 2. with overload of function isBitmaskEnum
constexpr std::true_type isBitmaskEnum(Access);
```
> feat: define enum as bitmask by function overload

- include/open62541pp/Common.h
- include/open62541pp/NodeIds.h
- include/open62541pp/types/NodeId.h
- tests/Types.cpp
- tools/gen_nodeids.py
Decouple `NodeId` from `NodeIds.h` header
> refactor: `getNamespace` overloads for node id enums

- include/open62541pp/services/Attribute.h
- tests/Services.cpp
This error included, for example, `services::readValueAsync`.
> fix: type error in highlevel attribute async read functions

- include/open62541pp/MonitoredItem.h
- include/open62541pp/services/MonitoredItem.h
- include/open62541pp/types/Composed.h
- tests/Types.cpp
- Remove deprecated `MonitoringParameters` type alias to avoid shadowing of OPC UA type [`MonitoringParameter`](https://reference.opcfoundation.org/Core/Part4/v104/docs/7.16)
- Add missing wrapper classes of monitored item service set:
- `MonitoringParameters` 
- `MonitoredItemCreateRequest`
- `MonitoredItemCreateResult`
- `CreateMonitoredItemsRequest`
- `CreateMonitoredItemsResponse`
- `MonitoredItemModifyRequest`
- `MonitoredItemModifyResult`
- `ModifyMonitoredItemsRequest`
- `ModifyMonitoredItemsResponse`
- `SetMonitoringModeRequest`
- `SetMonitoringModeResponse`
- `SetTriggeringRequest`
- `SetTriggeringResponse`
- `DeleteMonitoredItemsRequest`
- `DeleteMonitoredItemsResponse`
> feat!: remove deprecated MonitoringParameters type alias

- include/open62541pp/services/MonitoredItem.h
- src/services/MonitoredItem.cpp
- tests/Services.cpp
Just use the symmetric functions for both `Client` and `Server` and pass `0U` as the `subscriptionId`:
```diff
- services::createMonitoredItemDataChange(server, ...)
+ services::createMonitoredItemDataChange(server, 0U, ...)
- services::deleteMonitoredItem(server, ...)
+ services::deleteMonitoredItem(server, 0U, ...)
```
> feat!: remove Server overloads in MonitoredItem service set

- include/open62541pp/services/Subscription.h
- include/open62541pp/services/detail/SubscriptionContext.h
- include/open62541pp/types/Composed.h
- src/services/Subscription.cpp
- tests/Services.cpp
New function parameter in `services::createSubscription`:
```diff
[[nodiscard]] Result<uint32_t> createSubscription(
Client& connection,
SubscriptionParameters& parameters,
bool publishingEnabled = true,
+    StatusChangeNotificationCallback statusChangeCallback = {},
DeleteSubscriptionCallback deleteCallback = {}
);
```
> feat!: add subscription status change notification callback

- include/open62541pp/services/MonitoredItem.h
- include/open62541pp/services/detail/ResponseHandling.h
- src/services/MonitoredItem.cpp
- src/services/Subscription.cpp
- tests/Services.cpp
New monitored item service functions using raw requests/responses:
```cpp
CreateMonitoredItemsResponse createMonitoredItemsDataChange(
Client& connection,
const CreateMonitoredItemsRequest& request,
DataChangeNotificationCallback dataChangeCallback,
DeleteMonitoredItemCallback deleteCallback = {}
);
CreateMonitoredItemsResponse createMonitoredItemsEvent(
Client& connection,
const CreateMonitoredItemsRequest& request,
EventNotificationCallback eventCallback,
DeleteMonitoredItemCallback deleteCallback = {}
);
ModifyMonitoredItemsResponse modifyMonitoredItems(
Client& connection, const ModifyMonitoredItemsRequest& request
) noexcept;
SetMonitoringModeResponse setMonitoringMode(
Client& connection, const SetMonitoringModeRequest& request
) noexcept;
SetTriggeringResponse setTriggering( …
```
> feat: raw monitoreditem service

- CMakeLists.txt
- CONTRIBUTING.md
- README.md
- doc/CMakeLists.txt
- doc/DoxygenLayout_open62541.xml
- doc/async_model.md
- doc/overview.dox
Use `open62541pp` as project name consistently.
> chore: consistent project name

- examples/client_browse.cpp
- examples/client_connect.cpp
- examples/client_minimal.cpp
- examples/custom_datatypes/client_custom_datatypes.cpp
- examples/custom_datatypes/server_custom_datatypes.cpp
- examples/events/server_events.cpp
- examples/method/client_method.cpp
- examples/method/client_method_async.cpp
- examples/method/server_method.cpp
- examples/server.cpp
- examples/server_accesscontrol.cpp
- examples/server_datasource.cpp
- examples/server_instantiation.cpp
- examples/server_minimal.cpp
- examples/server_valuecallback.cpp
- include/open62541pp/Client.h
- include/open62541pp/Server.h
- tests/Node.cpp
- tests/Server.cpp
- tests/Session.cpp
`Node`s should be created with its constructor and decoupled from `Client` and `Server`.
Following member functions are deprecated and will be removed in the future:
- `Client::getNode(NodeId id)`
- `Client::getRootNode()`
- `Client::getObjectsNode()`
- `Client::getTypesNode()`
- `Client::getViewsNode()`
- `Server::getNode(NodeId id)`
- `Server::getRootNode()`
- `Server::getObjectsNode()`
- `Server::getTypesNode()`
- `Server::getViewsNode()`
> feat!: deprecate Client::get*Node, Server::get*Node

- include/open62541pp/Server.h
- tests/Event.cpp
`Event`s should be created with its constructor and decoupled from `Server`.
Following member function is deprecated and will be removed in the future: `Server::createEvent(const NodeId& eventType)`
> feat!: deprecate Server::createEvent

- examples/client_connect.cpp
- include/open62541pp/Client.h
- include/open62541pp/types/Composed.h
- src/Client.cpp
- src/ClientConfig.h
- tests/Client.cpp
- tests/Types.cpp
Add `Client::setUserIdentityToken` to define the authentification method with UserIdentityTokens before calling `Client::connect`.
```cpp
/// Set anonymous identity token.
void Client::setUserIdentityToken(AnonymousIdentityToken token);
/// Set username/password identity token.
void Client::setUserIdentityToken(UserNameIdentityToken token);
/// Set X.509 identity token.
void Client::setUserIdentityToken(X509IdentityToken token);
/// Set issued identity token.
void Client::setUserIdentityToken(IssuedIdentityToken token);
```
> feat: Client::setUserIdentityToken

- include/open62541pp/Client.h
Deprecate `Client::connect` with login in favor of the more generic approach with UserIdentityTokens:
```cpp
opcua::Client client;
// old: connect with username credentials
client.connect(endpointUrl, {"username", "password"});
// new: set UserIdentityToken and connect afterwards
client.setUserIdentityToken(opcua::UserNameIdentityToken("username", "password"));
client.connect(endpointUrl);
> feat!: deprecate Client::connect with login, use Client::setUserIdentityToken instead

- include/open62541pp/TypeConverter.h
- include/open62541pp/types/Builtin.h
- src/types/Builtin.cpp
- src/types/NodeId.cpp
- tests/Config.cpp
- tests/Types.cpp
An implicit conversion function to `std::string_view` already exists.
Use `static_cast<std::string_view>(str)` for explicit conversions.
> feat!: deprecate String::get()

- include/open62541pp/types/Builtin.h
- src/types/Builtin.cpp
An implicit conversion function to `std::string_view` already exists.
Use `static_cast<std::string_view>(xml)` for explicit conversions.
> feat!: deprecate XmlElement::get()

- include/open62541pp/types/Builtin.h
- tests/Types.cpp
Make `String`, `ByteString` and `XMLElement` fully STL-compatible by adding following typedefs and member functions:
```cpp
using value_type             = CharT;  // char for String and XmlElement, uint8_t for ByteString
using size_type              = size_t;
using difference_type        = std::ptrdiff_t;
using pointer                = value_type*;
using const_pointer          = const value_type*;
using reference              = value_type&;
using const_reference        = const value_type&;
using iterator               = pointer;
using const_iterator         = const_pointer;
using reverse_iterator       = std::reverse_iterator<iterator>;
using const_reverse_iterator = std::reverse_iterator<const_iterator>;
size_t size() const noexcept;
size_t length() const noexcept;
bool empty() const …
```
> feat: STL-compatible interface for String, ByteString, XMLElement

- include/open62541pp/types/Builtin.h
- tests/Types.cpp
Rename `NumericRange::get()` -> `NumericRange::dimensions()`.
> feat!: rename NumericRange::get -> dimensions

- include/open62541pp/types/Builtin.h
- tests/Types.cpp
An implicit conversion function to `std::string_view` already exists.
Use `static_cast<std::string_view>(str)` for explicit conversions.
> feat!: deprecate ByteString::get()

- include/open62541pp/types/Builtin.h
- src/types/Builtin.cpp
- tests/DataType.cpp
- tests/Types.cpp
Remove `ByteString` member functions:
- `ByteString::fromFile`
- `ByteString::toFile`
Now that the `ByteString` has a STL-compatible interface (#330), it's pretty easy to implement reading from files and writing to files:
```cpp
// write
const ByteString bs("XYZ");
std::ofstream fp("bytestring.bin", std::ios::binary);
fp.write(reinterpret_cast<const char*>(bs.data()), bs.length());
// read
std::ifstream fp("bytestring.bin", std::ios::binary);
const ByteString bsRead(std::istreambuf_iterator<char>(fp)), (std::istreambuf_iterator<char>()));
```
> feat!: remove ByteString::fromFile, ByteString::toFile

- .github/workflows/open62541-compatibility.yml
- include/open62541pp/AccessControl.h
- include/open62541pp/Crypto.h
- include/open62541pp/Server.h
- include/open62541pp/plugins/PluginAdapter.h
- src/AccessControl.cpp
- src/ClientConfig.h
- src/Crypto.cpp
- src/CustomDataTypes.h
- src/Logger.cpp
- src/Server.cpp
- src/ServerConfig.h
- src/Session.cpp
- src/plugins/LoggerAdapter.h
- src/plugins/PluginManager.h
- tests/CMakeLists.txt
- tests/Client.cpp
- tests/ClientService.cpp
- tests/Crypto.cpp
- tests/Node.cpp
- tests/PluginManager.cpp
- tests/Server.cpp
- tests/Services.cpp
- tests/Session.cpp
- tests/Subscription_MonitoredItem.cpp
Update library to be compatible with open62541 v1.4.
Following interface changes were introduced:
- Deprecate `Server::setCustomHostname` because it's not supported in v1.4 anymore
- Remove `keySizeBits` parameter from function `crypto::createCertificate`
> feat!: open62541 v1.4 compatibility

- .clang-tidy
- examples/client_subscription.cpp
- examples/events/client_eventfilter.cpp
- include/open62541pp/Event.h
- include/open62541pp/MonitoredItem.h
- include/open62541pp/Node.h
- include/open62541pp/Session.h
- include/open62541pp/Subscription.h
- src/Event.cpp
- src/MonitoredItem.cpp
- src/Subscription.cpp
- tests/Node.cpp
Following types store the server/client connection as a reference which makes them non-copyable and non-movable:
- `Node`
- `Event`
- `Subscription`
- `MonitoredItem`
- `Session`
This PR replaces the reference with a pointer to make the types copyable and movable:
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-constref
> feat: copyable/movable types

- include/open62541pp/client.hpp
- include/open62541pp/plugin/log_default.hpp
- include/open62541pp/server.hpp
- src/client.cpp
- src/client_config.hpp
- src/server.cpp
- src/server_config.hpp
Rename `Logger` to `LogFunction`.
The name `Logger` was a ambiguous, because it refers to `UA_Logger`/`Logger` the plugin.
> refactor!: rename Logger -> LogFunction

- include/open62541pp/client.hpp
- include/open62541pp/plugin/log.hpp
- include/open62541pp/server.hpp
- src/plugin/accesscontrol.cpp
- src/plugin/log.cpp
- tests/logger.cpp
- tests/plugin_log.cpp
- tests/server.cpp
The usage of `log` was mainly internal. I expect that users plug in their own logging system and don't use open62541pp's log functions. Use `UA_LOG_*` if you still want to use the server's and client's loggers.
> feat!: remove log function overloads

- CHANGELOG.md
- include/open62541pp/plugin/log_default.hpp
Don't break existing code by removing `Logger` type alias completely. Keep it but deprecate it.
> refactor: keep deprecated Logger alias

- include/open62541pp/datatype.hpp
- include/open62541pp/server.hpp
- src/client.cpp
- src/plugin/accesscontrol.cpp
- src/server.cpp
- tests/client.cpp
- tests/plugin_accesscontrol.cpp
- tests/server.cpp
Open62541 provides a context pointer in `UA_ServerConfig` which is used to store a pointer to the underlying connection of the `Server` connection. Therefore, the `Server` instance can be retrieved from a `UA_Server` instance.
This is a workaround for open62541 v1.0-v1.2, where the context pointer didn't exist. Instead, the node context of the `Server` object (`UA_NS0ID_SERVER`) is used. This workaround is also used in `QUaServer`: https://github.com/QUaServer/QUaServer/blob/master/src/wrapper/quaserver.cpp#L1337
> refactor: workaround to get Server instance from UA_Server* for v1.0-v1.2

- include/open62541pp/plugin/accesscontrol.hpp
- include/open62541pp/plugin/log.hpp
- include/open62541pp/plugin/pluginadapter.hpp
- src/client.cpp
- src/client_config.hpp
- src/datatype.cpp
- src/plugin/accesscontrol.cpp
- src/plugin/create_certificate.cpp
- src/plugin/log.cpp
- src/server_config.hpp
- tests/CMakeLists.txt
- tests/plugin_accesscontrol.cpp
- tests/plugin_log.cpp
- tests/pluginadapter.cpp
- tests/server.cpp
Add boolean `ownsAdapter` parameter to `PluginAdapter::create` function to optionally move the adapter ownership to the native plugin.
```diff
- virtual T PluginAdapter::create() = 0;
+ virtual T PluginAdapter::create(bool ownsAdapter) = 0;
```
> refactor: optionally move adapter ownership to plugin

- doc/CMakeLists.txt
- include/open62541pp/client.hpp
- include/open62541pp/server.hpp
- src/client.cpp
- src/plugin/accesscontrol.cpp
- src/server.cpp
- tests/client_server_common.cpp
Convert native `UA_Client*`/`UA_Server*` pointer to it's wrapper instance with:
```cpp
Client* asWrapper(UA_Client* client) noexcept;
Server* asWrapper(UA_Server* server) noexcept;
```
The implementation makes use of the context pointers `UA_ClientConfig::clientContext` and `UA_ServerConfig::context`.
If the native pointer is not owned by a wrapper instance, the behavior is undefined.
> feat: asWrapper overloads for UA_Client*/UA_Server*

- include/open62541pp/client.hpp
- include/open62541pp/services/detail/response_handling.hpp
- include/open62541pp/services/subscription.hpp
- include/open62541pp/subscription.hpp
- src/client.cpp
- src/services_subscription.cpp
- tests/services_monitoreditem.cpp
- tests/subscription_monitoreditem.cpp
Use the raw service to inspect the revised parameters.
> feat!: don't revise subscription parameters

- include/open62541pp/services/monitoreditem.hpp
- include/open62541pp/services/subscription.hpp
- include/open62541pp/subscription.hpp
- src/client.cpp
- src/services_subscription.cpp
- tests/services_monitoreditem.cpp
- tests/services_subscription.cpp
- tests/subscription_monitoreditem.cpp
- return `CreateSubscriptionResponse` from all `services::createSubscription` overloads
- return `ModifySubscriptionResponse` from all `services::modifySubscription` overloads
> feat!: return raw responses from subscription service function overloads

- include/open62541pp/client.hpp
- include/open62541pp/server.hpp
- src/client.cpp
- src/server.cpp
- tests/client_server_common.cpp
Convert wrapper pointer `Client*`/`Server*` to native pointer with:
```cpp
UA_Client* asNative(Client* client) noexcept;
UA_Server* asNative(Server* server) noexcept;
```
> feat: asNative overloads for Client*/Server*

- include/open62541pp/client.hpp
- include/open62541pp/server.hpp
- src/client.cpp
- src/server.cpp
- tests/client_server_common.cpp
Just use `Client::handle`/`Server::handle`.
This reverts commit e77944edd296a866689ec8b0d8eb4c3204a09830.
> revert: asNative overloads for Client*/Server*

- include/open62541pp/client.hpp
- include/open62541pp/detail/client_utils.hpp
- include/open62541pp/detail/server_utils.hpp
- include/open62541pp/server.hpp
- include/open62541pp/services/detail/client_services.hpp
- src/client.cpp
- src/server.cpp
- tests/client_server_common.cpp
- tests/clientservice.cpp
The header `client_services.hpp` is included in all services headers mainly for async implementations. This PR removes the `client.hpp` dependency, which makes the services headers agnostic to both `Client` and `Server`.
> refactor: minimize client services dependencies

- include/open62541pp/services/detail/response_handling.hpp
- include/open62541pp/services/monitoreditem.hpp
- include/open62541pp/subscription.hpp
- src/services_monitoreditem.cpp
- tests/services_monitoreditem.cpp
Return `MonitoredItemCreateResult` from `services::createMonitoredItemDataChange`/`services::createMonitoredItemEvent` to allow further diagnostics like checking the revised parameters.
```cpp
const auto result = services::createMonitoredItemDataChange(/* ... */);
result.getStatusCode().throwIfBad();  // check status code
result.getMonitoredItemId();
result.getRevisedSamplingInterval();
result.getRevisedQueueSize();
// ...
```
> feat!: return MonitoredItemCreateResult from services::createMonitoredItem*

- include/open62541pp/services/monitoreditem.hpp
- tests/services_monitoreditem.cpp
Has no benefit, just use `services::setTriggering` with a `SetTriggeringRequest` instead.
> feat!: remove services::setTriggering overload

- include/open62541pp/monitoreditem.hpp
- include/open62541pp/services/monitoreditem.hpp
- src/services_monitoreditem.cpp
- tests/services_monitoreditem.cpp
Return `MonitoredItemModifyResult ` from `services::modifyMonitoredItem` to allow further diagnostics like checking the revised parameters.
```cpp
const auto result = services::modifyMonitoredItem(/* ... */);
result.getStatusCode().throwIfBad();  // check status code
result.getRevisedSamplingInterval();
result.getRevisedQueueSize();
// ...
```
> feat!: return MonitoredItemModifyResult from services::modifyMonitoredItem

- include/open62541pp/services/view.hpp
- src/services_view.cpp
- tests/CMakeLists.txt
- tests/services_view.cpp
Return `BrowseResult` instead of `Result<BrowseResult>` from `services::browse`/`services::browseNext` overloads.
> feat!: return BrowseResult from browse/browseNext overloads

- include/open62541pp/node.hpp
- include/open62541pp/services/view.hpp
- src/services_view.cpp
- tests/services_view.cpp
Return `BrowsePathResult` instead of `Result<BrowsePathResult>` from `services::translateBrowsePathToNodeIds`/`services::browseSimplifiedBrowsePath` overloads.
> feat!: return BrowsePathResult from translateBrowsePathToNodeIds/browseSimplifiedBrowsePath overloads

- include/open62541pp/services/view.hpp
- tests/services_view.cpp
Deprecate `services::browseRecursive` because it can not be implemented for clients.
Use `UA_Server_browseRecursive` if you need this feature.
> feat!: deprecate browseRecursive

- include/open62541pp/monitoreditem.hpp
- include/open62541pp/node.hpp
- include/open62541pp/services/attribute.hpp
- include/open62541pp/services/attribute_highlevel.hpp
- include/open62541pp/services/detail/response_handling.hpp
- include/open62541pp/services/monitoreditem.hpp
- include/open62541pp/services/nodemanagement.hpp
- include/open62541pp/services/subscription.hpp
- include/open62541pp/services/view.hpp
- include/open62541pp/subscription.hpp
- src/services_attribute.cpp
- src/services_monitoreditem.cpp
- src/services_nodemanagement.cpp
- src/services_subscription.cpp
- tests/node.cpp
- tests/services_attribute.cpp
- tests/services_monitoreditem.cpp
- tests/services_nodemanagement.cpp
- tests/services_subscription.cpp
- tools/gen_attribute_highlevel.py
Just return a `StatusCode` instead of `Result<void>` if possible. `Result<void>` as a return type just wraps a returned `StatusCode`.
The `Result<T>` type shines in scenarios, where a result and a `StatusCode` have to be returned simultaneously - let's only use it there.
> feat!: return StatusCode instead of Result<void>

- doc/async_model.md
- doc/fragments/alias_completiontoken.dox
- examples/method/client_method_async.cpp
- examples/server_datasource.cpp
- include/open62541pp/services/attribute.hpp
- include/open62541pp/services/attribute_highlevel.hpp
- include/open62541pp/services/method.hpp
- include/open62541pp/services/monitoreditem.hpp
- include/open62541pp/services/nodemanagement.hpp
- include/open62541pp/services/subscription.hpp
- include/open62541pp/services/view.hpp
- include/open62541pp/subscription.hpp
- src/client.cpp
- tests/client_service.cpp
- tests/node.cpp
- tests/services_attribute.cpp
- tests/services_helper.cpp
- tests/services_method.cpp
- tests/services_monitoreditem.cpp
- tests/services_nodemanagement.cpp
- tests/services_subscription.cpp
- tests/services_view.cpp
- tools/gen_attribute_highlevel.py
Remove all default arguments of functions in the `opcua::services` namespace. The previous default arguments are mentioned in the function documentation.
Why? The completion token of async functions is always the last function parameter. So all function arguments, even the default ones, have to be provided for async function calls. This makes it hard to switch between sync and async behavior.
> feat!: remove default arguments of functions in services namespace

- .clang-format
- include/open62541pp/services/monitoreditem.hpp
- include/open62541pp/typewrapper.hpp
Adapt and apply clang-format config options for version 14 and later.
> style: refine format rules

- include/open62541pp/plugin/create_certificate.hpp
- src/plugin/create_certificate.cpp
- tests/plugin_create_certificate.cpp
All types and functions are now available in namespace `opcua`.
> feat!: remove crypto namespace

- examples/client_async.cpp
- examples/client_subscription.cpp
- examples/events/client_eventfilter.cpp
- include/open62541pp/common.hpp
- include/open62541pp/detail/client_context.hpp
- include/open62541pp/detail/server_context.hpp
- include/open62541pp/monitoreditem.hpp
- include/open62541pp/services/detail/monitoreditem_context.hpp
- include/open62541pp/services/detail/request_handling.hpp
- include/open62541pp/services/detail/subscription_context.hpp
- include/open62541pp/services/monitoreditem.hpp
- include/open62541pp/services/subscription.hpp
- include/open62541pp/subscription.hpp
- include/open62541pp/types_composed.hpp
- src/monitoreditem.cpp
- src/services_monitoreditem.cpp
- src/services_subscription.cpp
- tests/services_monitoreditem.cpp
- tests/services_subscription.cpp
- tests/subscription_monitoreditem.cpp
The type [`IntegerId`](https://reference.opcfoundation.org/Core/Part4/v105/docs/7.19) is an alias for `uint32_t` and is used in the OPC UA standard for identifiers like:
- subscription id
- monitored item id
- client handle
- ...
> feat: IntegerId alias (uint32_t)

- include/open62541pp/deprecated.hpp.in
`deprecated.hpp` included the deprecated header `Config.h`, which lead to another deprecation warning.
> fix: config include in deprecated.hpp

- .gitmodules
- doc/Doxyfile.in
- doc/Doxyfile_open62541.in
Prevents accidental includes of documentation snippets of the library.
> build: move doxygen-awesome-css submodule to 3rdparty folder

- include/open62541pp/client.hpp
- include/open62541pp/detail/client_context.hpp
- src/client.cpp
- tests/client.cpp
Define a subscription inactivity callback via `Client::onSubscriptionInactive`.
The callback is called when the client does not receive a publish response after the defined delay of `(publishingInterval * maxKeepAliveCount) + UA_ClientConfig::timeout)`.
Closes #455.
> feat: Client::onSubscriptionInactive

- include/open62541pp/services/view.hpp
- src/services_view.cpp
- tests/services_view.cpp
As the name implies, `browseAll` should be used to retrieve all references. Use `browse` to get only a limited set of references.
> feat!: remove maxReferences parameter from services::browseAll

- include/open62541pp/types.hpp
- tests/types_builtin.cpp
Replace inheritance from `StringWrapper` with CRTP mixin class `StringLikeMixin`.
> refactor: replace StringWrapper with CRTP mixin class

- include/open62541pp/subscription.hpp
- src/subscription.cpp
- tests/subscription_monitoreditem.cpp
Remove `get` prefix of `Subscription::getMonitoredItems()` -> `Subscription::monitoredItems()`.
See #459.
> feat!: remove get prefix of Subscription::getMonitoredItems

- include/open62541pp/server.hpp
- src/server.cpp
- tests/session.cpp
Remove `get` prefix of `Server::getSessions()` -> `Server::sessions()`.
See #459.
> feat!: remove get prefix of Server::getSessions

- include/open62541pp/client.hpp
- src/client.cpp
- tests/subscription_monitoreditem.cpp
Remove `get` prefix of `Client::getSubscriptions()` -> `Client::subscriptions()`.
See #459.
> feat!: remove get prefix of Client::getSubscriptions

- include/open62541pp/client.hpp
- include/open62541pp/server.hpp
- src/client.cpp
- src/server.cpp
- tests/client.cpp
- tests/server.cpp
Remove `get` prefix of `Client/Server::getNamespaceArray()` -> `Client/Server::namespaceArray()`.
See #459.
> feat!: remove get prefix of Client::getNamespaceArray, Server::getNamespaceArray

- examples/client_subscription.cpp
- examples/events/client_eventfilter.cpp
- include/open62541pp/monitoreditem.hpp
- src/monitoreditem.cpp
Remove `get` prefix of `MonitoredItem` getters:
- `MonitoredItem::getNodeId()` -> `MonitoredItem::nodeId()`
- `MonitoredItem::getAttributeId()` -> `MonitoredItem::attributeId()`
See #459.
> feat!: remove get prefix of MonitoredItem getters

- include/open62541pp/typewrapper.hpp
Remove `get` prefix of `TypeWrapper::getTypeIndex()` -> `TypeWrapper::typeIndex()`.
See #459.
> feat!: remove get prefix of TypeWrapper::getTypeIndex

- include/open62541pp/detail/types_handling.hpp
- include/open62541pp/types.hpp
- src/types.cpp
- tests/types_builtin.cpp
Implement `NumericRange` as `Wrapper<UA_NumericRange>` to be used with `asWrapper`/`asNative`.
Closes #479.
> feat: NumericRange as wrapper

- include/open62541pp/types.hpp
- include/open62541pp/ua/nodeids.hpp
- tools/gen_nodeids.py
Rename `getNamespace` -> `namespaceOf` to remove `get` prefix.
See #459.
The function is used internally to retrieve the namespace index of a `enum class` of numeric node ids, e.g. `ObjectNodeId`. This shouldn't break existing code, still it's in the public API so we mark is as a breaking change.
> feat!: rename getNamespace -> namespaceOf

- include/open62541pp/detail/contextmap.hpp
- include/open62541pp/detail/server_context.hpp
- src/server.cpp
Protect session registry container with a mutex to avoid data races.
> fix: thread-safe session registry

- examples/client_subscription.cpp
- examples/method/server_method.cpp
- examples/server_datasource.cpp
- examples/typeconversion.cpp
- include/open62541pp/bitmask.hpp
- include/open62541pp/detail/iterator.hpp
- include/open62541pp/node.hpp
- include/open62541pp/services/detail/attribute_handler.hpp
- include/open62541pp/span.hpp
- include/open62541pp/types.hpp
- src/client.cpp
- src/server.cpp
- tests/CMakeLists.txt
- tests/iterator.cpp
- tests/server.cpp
- tests/services_method.cpp
- tests/types_builtin.cpp
As discussed in #491.
`Variant::to<T>` replaces the copy getters:
- `Variant::getScalarCopy<T>()` -> `Variant::to<T>()`
- `Variant::getArrayCopy<T>()` -> `Variant::to<std::vector<T>>()`
```cpp
opcua::Variant varScalar("test123");
auto str = varScalar.to<std::string>();
std::vector<int> array{1, 2, 3};
opcua::Variant varArray(array);
auto lst = varArray.to<std::list<int>>();
auto vec = varArray.to<std::vector<int>>();
```
> feat!: add Variant::to<T> to retrieve/convert scalar and array values

- include/open62541pp/types.hpp
- tests/types_builtin.cpp
Use `Variant::setArrayCopy` instead.
`Variant::setValue*` is mainly used as a universal setter interface. The type category scalar/array is determined by the template type. If a iterator pair is passed, it's clearly an array type. In this case, the user should just the `Variant::setArrayCopy` member function.
> feat!: remove Variant::setValueCopy overload with iterator pair

- examples/method/client_method.cpp
- examples/method/client_method_async.cpp
- examples/server_accesscontrol.cpp
- include/open62541pp/node.hpp
- include/open62541pp/services/detail/attribute_handler.hpp
- include/open62541pp/types.hpp
- include/open62541pp/ua/types.hpp
- src/event.cpp
- tests/node.cpp
- tests/services_attribute.cpp
- tests/services_method.cpp
- tests/services_monitoreditem.cpp
- tests/session.cpp
- tests/types_builtin.cpp
- tests/ua_types.cpp
The factory functions `fromScalar`/`fromArray` are now deprecated in favor Variant's new universal constructor from #384:
- `Variant::fromScalar(...)` -> use `Variant(...)` instead
- `Variant::fromArray(...)` -> use `Variant(...)` instead
- `DataValue::fromScalar(...)` -> use `DataValue(Variant(...))` instead
- `DataValue::fromArray(...)` -> use `DataValue(Variant(...))` instead
> feat!: deprecate fromScalar/fromArray in favor of Variant's new universal constructor

- README.md
- include/open62541pp/node.hpp
- include/open62541pp/types.hpp
- tests/types_builtin.cpp
This PR introduces a new approach for handling non-owning references in the `Variant` class, proposed by @chandryan in #489. Instead of using the `ReferenceTag` tag to distinguish between owning and non-owning storage mechanisms, we now use pointer semantics to achieve the same functionality.
The `Variant` constructor and `Variant::assign` function are now able to accept pointers directly, providing a more intuitive way to assign non-owning references.
```cpp
// Assigning a value without copy
int value = 5;
opcua::Variant var(opcua::reference, value);  // Old way using ReferenceTag
opcua::Variant var(&value);                   // New way using pointer
var.assign(opcua::reference, vec);            // Old way using ReferenceTag
var.assign(&vec);                             // New way using …
```
> feat!: use pointer semantics instead of ReferenceTag within Variant

- include/open62541pp/types.hpp
- src/plugin/accesscontrol_default.cpp
- tests/client.cpp
- tests/types_builtin.cpp
- tests/ua_types.cpp
Rename `isEmpty` member functions to `empty()` for consistency:
- `Variant::isEmpty()` -> `Variant::empty()`
- `ExtensionObject::isEmpty()` -> `ExtensionObject::empty()`
The old functions are deprecated and will be removed in the future.
> feat!: rename isEmpty -> empty

- include/open62541pp/types.hpp
Support conversions of `std::basic_string<char, Traits, Allocator>` and `std::basic_string_view<char, Traits>` with custom `Traits` and `Allocator` types.
> feat: string conversions with custom Traits and Allocator types

- examples/method/server_method.cpp
- examples/server_datasource.cpp
- examples/typeconversion.cpp
- include/open62541pp/types.hpp
- tests/server.cpp
- tests/services_method.cpp
- tests/types_builtin.cpp
Use assignment operator to assign scalars/arrays to `Variant` as discussed in #489:
```cpp
opcua::Variant var;
int value = 5;
var.assign(value);   // Old way with copy
var.assign(&value);  // Old way without copy
var = value;         // New way with copy
var = &value;        // New way without copy
std::array<int> array{1, 2, 3};
var.assign(array);   // Old way with copy
var.assign(&array);  // Old way without copy
var = array;         // New way with copy
var = &array;        // New way without copy
```
> feat: Variant assignment operator for scalars/arrays

- include/open62541pp/services/detail/request_handling.hpp
- include/open62541pp/subscription.hpp
- include/open62541pp/types.hpp
- src/client.cpp
- src/ua_types.cpp
- tests/plugin_accesscontrol.cpp
- tests/services_monitoreditem.cpp
- tests/types_builtin.cpp
- tests/ua_types.cpp
Add universal `ExtensionObject` constructors that replace the factory functions `fromDecoded`/`fromDecodedCopy`.
It uses the same approach as in #497 with pointer semantics to distinguish between owning and non-owning storage mechanisms:
```cpp
opcua::String str("test");
// Old way
auto obj1 = opcua::ExtensionObject::fromDecoded(str);      // No copy
auto obj2 = opcua::ExtensionObject::fromDecodedCopy(str);  // Copy
// New way
opcua::ExtensionObject obj3(&str);  // No copy
opcua::ExtensionObject obj4(str);   // Copy
```
The factory functions `ExtensionObject::fromDecoded` and `ExtensionObject::fromDecodedCopy` are marked deprecated now and will be removed in the future.
> feat!: universal ExtensionObject constructor

- include/open62541pp/types.hpp
- tests/types_builtin.cpp
Retrieve encoded body of `ExtensionObject` in binary and XML encoding with:
- `ExtensionObject::encodedBinary()`
- `ExtensionObject::encodedXml()`
> feat: ExtensionObject::encodedBinary, ExtensionObject::encodedXml

- include/open62541pp/types.hpp
- tests/types_builtin.cpp
Add assignment operators for `String` and `XmlElement` to assign string literals (`const char*`) and `std::string_view` (or anything that is convertible to, e.g. `std::string`).
```cpp
opcua::String str;
str = "test123";
str = std::string_view("test123");
str = std::string("test123");
```
> feat: String/XmlElement assignment operator for const char* and string_view

- tests/helper/server_client_setup.hpp
- tests/services_monitoreditem.cpp
- tests/subscription_monitoreditem.cpp
Introduce a helper function that keeps calling a client's or server's `runIterate` function until a condition or a timeout occurs.
Draft status with demo code related to https://github.com/open62541pp/open62541pp/issues/511
> test: increase robustness of tests using `runIterate`

- include/open62541pp/result.hpp
- src/server.cpp
Arthur O’Dwyer convinced me with his excellent blog post:
https://quuxplusone.github.io/blog/2024/12/08/should-expected-be-nodiscard/
> Discarding a result is usually OK. Discarding an error, on the other hand, can be very bad, and should always be done explicitly!
> feat: mark Result class as nodiscard

- examples/server_datasource.cpp
- include/open62541pp/plugin/nodestore.hpp
- src/server.cpp
- tests/server.cpp
The parameter range is optional, therefore it should be passed by pointer, not by reference.
As discussed in #515.
> feat!: pass optional range as pointer to DataSource functions

- include/open62541pp/detail/open62541/push_options.h
If open62541pp is imported in a project which relies on such a macro, and it is not the first header to be imported, STL code may break.
If `NOMINMAX` is defined globally, then redefinition warning may be raised.
For instance with Visual Studio 2022 with MSVC compiler the following warning appears:
`warning C4005: 'NOMINMAX': macro redefinition`
> fix!: Avoid redefinition of NOMINMAX macro for Windows systems

- .github/workflows/ci.yml
- CHANGELOG.md
- include/open62541pp/detail/types_handling.hpp
- tests/types_handling.cpp
Fix undefined behavior in `detail::copyArray` with `src = nullptr` passed to `std::memcpy`.
> fix: undefined behavior in array handling

- CHANGELOG.md
- examples/client_subscription.cpp
- examples/events/client_eventfilter.cpp
- include/open62541pp/client.hpp
- include/open62541pp/server.hpp
- include/open62541pp/subscription.hpp
- src/subscription.cpp
- tests/subscription_monitoreditem.cpp
Decouple `Client`/`Server` from `Subscription` class.
Simplify subscription creation with `Subscription` constructor:
```diff
opcua::SubscriptionParameters subscriptionParameters{};
- opcua::Subscription sub = client.createSubscription(subscriptionParameters);
+ opcua::Subscription sub(client, subscriptionParameters);
```
Following functions are marked deprecated and will be removed in the future:
- `Client::createSubscription`
- `Server::createSubscription`
> feat!: create Subscription via constructor

- include/open62541pp/detail/ptr.hpp
- include/open62541pp/detail/server_context.hpp
- include/open62541pp/server.hpp
- src/server.cpp
- tests/server.cpp
Add overloads to optionally move ownership of the plugins to the server:
```diff
void Server::setVariableNodeValueCallback(const NodeId& id, ValueCallbackBase& callback);
+ void Server::setVariableNodeValueCallback(const NodeId& id, std::unique_ptr<ValueCallbackBase>&& callback);
void Server::setVariableNodeDataSource(const NodeId& id, DataSourceBase& source);
+ void Server::setVariableNodeDataSource(const NodeId& id, std::unique_ptr<DataSourceBase>&& source);
```
Closes #539.
> feat: move ownership of ValueCallback and DataSource to server

- doc/Doxyfile.in
- include/open62541pp/config.hpp.in
- include/open62541pp/types.hpp
- tests/types_builtin.cpp
Add factory function `Guid::parse` to parse `Guid` from its string representation, e.g. `C496578A-0DFE-4B8F-870A-745238C6AEAE`.
> feat: Guid::parse

- include/open62541pp/types.hpp
- src/types.cpp
- tests/types_builtin.cpp
Add factory functions `NodeId::parse`/`ExpandedNodeId::parse` to parse node ids from their string representations.
Closes #541.
> feat: NodeId::parse, ExpandedNodeId::parse

- include/open62541pp/detail/types_conversion.hpp
- include/open62541pp/detail/types_handling.hpp
- include/open62541pp/node.hpp
- include/open62541pp/services/detail/response_handling.hpp
- include/open62541pp/typeconverter.hpp
- include/open62541pp/typeregistry.hpp
- include/open62541pp/types.hpp
- include/open62541pp/typewrapper.hpp
- include/open62541pp/wrapper.hpp
- tests/typeregistry.cpp
- tests/types_handling.cpp
- Rename `detail::IsRegisteredType` -> `detail::IsRegistered`
- Rename `detail::IsConvertibleType` -> `detail::IsConvertible`
- Remove `constexpr bool is*` aliases, use `::value` instead
> refactor: simplify traits

- .github/workflows/ci.yml
- .github/workflows/open62541-compatibility.yml
- include/open62541pp/client.hpp
- include/open62541pp/server.hpp
- src/client.cpp
- src/server.cpp
- tests/client.cpp
- tests/server.cpp
Add constructors to create `Client` and `Server` from native instances:
```cpp
explicit Client::Client(UA_Client* native);
explicit Server::Server(UA_Server* native);
```
> feat: construct Client/Server from native

- include/open62541pp/types.hpp
- src/types.cpp
- tests/types_builtin.cpp
Explicitly convert to string with `opcua::toString` first.
> feat!: remove ostream overloads for Guid and XmlElement

- include/open62541pp/types.hpp
- src/plugin/accesscontrol_default.cpp
- tests/types_builtin.cpp
Use explicit conversion to `std::string_view` if required.
> feat!: remove ByteString <-> std::string_view equality operator overloads

- include/open62541pp/datatype.hpp
- include/open62541pp/detail/string_utils.hpp
- src/datatype.cpp
- src/string_utils.cpp
- tests/string_utils.cpp
Allow `typeName`s that are no string literals (known at compile time).
> fix: store typeName in DataType wrapper

- include/open62541pp/config.hpp.in
- include/open62541pp/datatype.hpp
- src/client.cpp
- src/datatype.cpp
- src/server.cpp
Allow `memberName`s that are no string literals (known at compile time).
> fix: store memberName in DataType wrapper

- examples/custom_datatypes/client_custom_datatypes.cpp
- examples/custom_datatypes/server_custom_datatypes.cpp
- include/open62541pp/client.hpp
- include/open62541pp/server.hpp
- src/client.cpp
- src/server.cpp
- tests/client_server_common.cpp
`customDataTypes` are part of the client/server config and not the client/server instance. Move method to config class:
```cpp
ClientConfig::addCustomDataTypes(Span<const DataType> types);
ServerConfig::addCustomDataTypes(Span<const DataType> types);
```
The old methods `Client::setCustomDataTypes` and `Server::setCustomDataTypes` are deprecated.
> feat: *Config::addCustomDataTypes

- include/open62541pp/types.hpp
- src/types.cpp
- tests/types_builtin.cpp
Avoid `#include <string>` in core headers.
> feat!: return String instead of std::string from wrapper type member functions

- examples/server_accesscontrol.cpp
- include/open62541pp/plugin/accesscontrol_default.hpp
- src/plugin/accesscontrol_default.cpp
- tests/client.cpp
- tests/plugin_accesscontrol.cpp
- tests/server.cpp
> feat!: use String instead of std::string for Login::username and password

- README.md
- examples/client_connect.cpp
- examples/client_minimal.cpp
- examples/server.cpp
- examples/server_instantiation.cpp
- examples/server_minimal.cpp
- examples/server_valuecallback.cpp
- include/open62541pp/node.hpp
- tests/node.cpp
- tests/server.cpp
Deprecate specialized `Node::readValue*` and `Node::writeValue*` functions.
The unified `Variant` API introduced in v0.17.0 is only slightly more verbose but more explicit:
- `Node::readValueScalar<T>()` -> `Node::readValue().to<T>()`
- `Node::readValueArray<T>()` -> `Node::readValue().to<std::vector<T>>()`
- `Node::writeValueScalar(const T& value)` -> `Node::writeValue(Variant(value))`
- `Node::writeValueArray(const T& array)` -> `Node::writeValue(Variant(array))`
> feat: deprecate specialized Node::readValue* and Node::writeValue* functions

- examples/custom_datatypes/server_custom_datatypes.cpp
- examples/server_accesscontrol.cpp
- examples/server_instantiation.cpp
- include/open62541pp/ua/types.hpp
- tests/node.cpp
The unified `Variant` API introduced in v0.17.0 is only slightly more verbose but more explicit:
- `VariableAttributes::setValueScalar(...)` -> `VariableAttributes::setValue(Variant{...})`
- `VariableAttributes::setValueArray(...)` -> `VariableAttributes::setValue(Variant{...})`
- `VariableTypeAttributes::setValueScalar(...)` -> `VariableTypeAttributes::setValue(Variant{...})`
- `VariableTypeAttributes::setValueArray(...)` -> `VariableTypeAttributes::setValue(Variant{...})`
> feat: deprecate specialized Variable*Attributes::setValue* functions

- include/open62541pp/client.hpp
- include/open62541pp/datatype.hpp
- include/open62541pp/monitoreditem.hpp
- include/open62541pp/server.hpp
- include/open62541pp/subscription.hpp
- include/open62541pp/types.hpp
- include/open62541pp/ua/types.hpp
Remove functions that have been deprecated at least since v0.17.0:
- Old `NodeId` identifier getter
- `*::fromScalar`, `*::fromArray`, `*::fromDecoded`, `*::fromDecodedCopy` factory functions
- `*::isEmpty` member functions
- `Variant::set*` functions
- `Variant::get*Copy` functions
- Member functions with `get` prefix
> feat!: remove deprecations ≤ v0.17.0

- include/open62541pp/detail/traits.hpp
- include/open62541pp/types.hpp
- include/open62541pp/ua/types.hpp
- src/string_utils.cpp
`TypeConverter` specialization to convert any string-like types to `String` if they meet following criteria:
- `begin()` and `end()` member functions (range)
- `data()` and `size()` member functions (continuous range)
- iterator value type must be `char*`
- `data()` must return a pointer of type `char*`
- constructible from `const char*`
- constructible from `const char*` and a length of type `size_t`
This is true, e.g. for `std::string`, `std::string_view`, `absl::string_view`, `boost::basic_string<char>`, ...
> feat: String type conversion for all string-like types

- include/open62541pp/datatype.hpp
Sometimes it's not possible to get the member pointer at compile time, and offsets may need to be used. This is especially true when using reflection to generate offsets, in which case there is no way to get a member pointer at compile time.
> feat: DataTypeBuilder::addField overloads with manual offsets

- include/open62541pp/types.hpp
- tests/typeconverter.cpp
String literals are null-terminated but runtime buffers may not. Check last char and trim null terminator.
> fix: trim null terminator of string literals in char[N] TypeConverter

- doc/guide/error_handling.md
- include/open62541pp/detail/server_context.hpp
- include/open62541pp/services/nodemanagement.hpp
- src/services_nodemanagement.cpp
- tests/services_attribute.cpp
- tests/services_method.cpp
- tests/services_nodemanagement.cpp
Support full function signature for method callbacks with `session`, `methodId` and `objectId`.
The type `MethodCallback` is now a variant that takes either the simple signature with only input and output arguments or the full signature.
Full signature:
```cpp
StatusCode(
Session& session,
Span<const Variant> input,
Span<Variant> output,
const NodeId& methodId,
const NodeId& objectId
)>
```
Closes #598.
> feat: MethodCallback with session, methodId and objectId

- src/client.cpp
- src/server.cpp
The default constructor of `ClientConfig`/`ServerConfig` is accidentally called when passing a config to the server/client constructor causing confusing log outputs.
Closes #600.
> fix: confusing log output when creating client/server with non-default config

- README.md
- examples/typeconversion.cpp
- include/open62541pp/typeconverter.hpp
- include/open62541pp/types.hpp
- tests/typeconverter.cpp
Add support and prefer return-by-value overloads in `TypeConverter`:
```cpp
template <>
struct TypeConverter<MyGuid> {
using NativeType = Guid;
// Return-by-value (preferred)
[[nodiscard]] static MyGuid fromNative(const Guid& src) { ... }
[[nodiscard]] static Guid toNative(const MyGuid& src) { ... }
// Reference-based fallback
static void fromNative(const Guid& src, MyGuid& dst) { ... }
static void toNative(const MyGuid& src, Guid& dst) { ... }
};
```
> feat: support return-by-value overloads in TypeConverter

- .github/workflows/open62541-compatibility.yml
- examples/server_accesscontrol.cpp
- src/plugin/accesscontrol_default.cpp
- src/server.cpp
- tests/client.cpp
- tests/server.cpp
Fixes two issues:
- `Error 'BadIdentityTokenInvalid' was returned during ActivateSession` in `server_accesscontrol` example (closes #610)
- `BadIdentityTokenInvalid` in CI with open62541 >= v1.4.6
> fix: access control with v1.4

- include/open62541pp/detail/types_handling.hpp
- include/open62541pp/span.hpp
- include/open62541pp/types.hpp
- tests/types_builtin.cpp
Move values to `Variant` if passed as rvalue reference (if possible).
> perf: move-aware variant construction and assignment

- include/open62541pp/types.hpp
- include/open62541pp/wrapper.hpp
- tests/types_builtin.cpp
The `&&` and `const&&` ref-qualified overloads for `Variant::scalar<T>()` move the value only if the `Variant` owns it; otherwise, they copy it.
> fix: move only owned scalars from Variant

- include/open62541pp/detail/types_handling.hpp
- include/open62541pp/types.hpp
- src/services_view.cpp
- tests/types_builtin.cpp
Strip `UA_EMPTY_ARRAY_SENTINEL` sentinel from data pointer/span returned by `Variant::data()` and `Variant::array<T>()`.
> fix: strip empty array sentinel from Variant data pointer

- include/open62541pp/services/detail/response_handling.hpp
- include/open62541pp/typeconverter.hpp
- include/open62541pp/typeregistry.hpp
- include/open62541pp/types.hpp
- include/open62541pp/wrapper.hpp
- tests/typeregistry.cpp
- tests/types_builtin.cpp
Move traits from namespace `opcua::detail` to `opcua` to make them public:
- `IsWrapper<T>` to check if a type is based on `Wrapper`
- `IsRegistered<T>` to check if a type is registered with a `TypeRegistry` template specialization
- `IsConvertible<T>` to check if a type is convertible with a `TypeConverter` template specialization
> feat: make traits IsWrapper, IsRegistered, IsConvertible public

- include/open62541pp/types.hpp
- tests/types_builtin.cpp
Avoid `<initializer_list>` include in commonly used `types.hpp` header.
> feat!: remove String constructor from initializer list

- CMakeLists.txt
- doc/examples.dox
- examples/CMakeLists.txt
- examples/server_callback.cpp
- include/open62541pp/callback.hpp
- include/open62541pp/detail/client_context.hpp
- include/open62541pp/detail/contextmap.hpp
- include/open62541pp/detail/server_context.hpp
- src/callback.cpp
- tests/CMakeLists.txt
- tests/callback.cpp
New header `open62541pp/callback.hpp` with free functions to define timed/repeated callbacks for both `Client` and `Server`:
- `addTimedCallback`
- `addRepeatedCallback`
- `changeRepeatedCallbackInterval`
- `removeCallback`
> feat: timed/repeated callbacks

- examples/server_callback.cpp
- include/open62541pp/types.hpp
- tests/types_builtin.cpp
Date arithmetic with `DateTime` and `std::chrono::duration`:
- Add `std::chrono::duration` to `DateTime`
- Substract `std::chrono::duration` from `DateTime`
- Substract two `DateTime` -> `std::chrono::duration`
Mark `DateTime` functions `constexpr` if possible.
> feat: date arithmetic with DateTime and std::chrono::duration

- include/open62541pp/client.hpp
- include/open62541pp/datatype.hpp
- include/open62541pp/server.hpp
- src/datatype.cpp
- tests/datatype.cpp
Add function overload set to find `UA_DataType` by `typeId`:
```cpp
const UA_DataType* findDataType(const NodeId& id) noexcept;
const UA_DataType* findDataType(const NodeId& id, const UA_DataTypeArray* custom) noexcept;
const UA_DataType* findDataType(Client& client, const NodeId& id) noexcept;
const UA_DataType* findDataType(Server& server, const NodeId& id) noexcept;
```
> feat: add findDataType overload set

- .github/workflows/ci.yml
> ci: don't run retired windows 2019 runner os
