doc/CMakeLists.txt, doc/Doxyfile.in, doc/Doxyfile_open62541.in, doc/prepare_open62541_header.py
Just for development purpose to browse and explore the open62541 API
=> Add Doxygen HTML docs for public open62541 API as CMake target

CMakeLists.txt, include/open62541pp/TypeWrapper.h, src/Variant.cpp
I updated open62541 to the latest stable version 1.3.5. There where only a few breaking changes which I fixed.
=> Update open62541 to v1.3.5

CMakeLists.txt, doc/DoxygenLayout.xml, include/open62541pp/Node.h, include/open62541pp/open62541pp.h, include/open62541pp/services/Attribute.h, include/open62541pp/services/NodeManagement.h, include/open62541pp/services/services.h, src/Node.cpp, src/services/Attribute.cpp, src/services/NodeManagement.cpp, tests/CMakeLists.txt, tests/Node.cpp, tests/Services.cpp
As discussed in #20 to prepare client implementation
=> feat: free functions in services namespace

CMakeLists.txt, doc/Doxyfile.in, doc/DoxygenLayout.xml, examples/CMakeLists.txt, examples/client_connect.cpp, examples/client_find_servers.cpp, examples/helper.h, include/open62541pp/Auth.h, include/open62541pp/Client.h, include/open62541pp/Node.h, include/open62541pp/Server.h, include/open62541pp/TypeWrapper.h, include/open62541pp/open62541pp.h, include/open62541pp/services/Attribute.h, include/open62541pp/services/NodeManagement.h, include/open62541pp/types/Composed.h, src/Client.cpp, src/CustomLogger.cpp, src/CustomLogger.h, src/Server.cpp, src/open62541_impl.h, src/services/Attribute.cpp, src/services/NodeManagement.cpp, tests/CMakeLists.txt, tests/Client.cpp, tests/Services.cpp, tests/TypeWrapper.cpp, tests/helper/Runner.h
Prior discussions in #20 and #23.
=> feat: basic client implementation

.github/workflows/ci.yml, CMakeLists.txt, README.md
Migrate from Coveralls to Codecov.
=> ci: coverage

CMakeLists.txt, include/open62541pp/open62541pp.h, include/open62541pp/types/ExtensionObject.h, src/types/ExtensionObject.cpp, tests/Types.cpp
Wrapper for `UA_ExtensionObject` with convenient getters and setters.
=> feat: ExtensionObject wrapper

.github/workflows/open62541-compatibility.yml, CHANGELOG.md, CMakeLists.txt
Update to latest open62541 release v.1.3.6.
=> feat: update to open62541 v1.3.6

src/Subscription.cpp, tests/Subscription_MonitoredItem.cpp
=> fix: incorrect monitoreditem ids

include/open62541pp/Client.h, src/Client.cpp, tests/Client.cpp
Add `Client::setTimeout` method to set `Client` response timeout.
=> feat: set client timeout

CHANGELOG.md, CMakeLists.txt, doc/CMakeLists.txt, doc/example.dox, examples/CMakeLists.txt, examples/client_method.cpp, examples/server_method.cpp, include/open62541pp/Node.h, include/open62541pp/services/Method.h, include/open62541pp/services/MonitoredItem.h, include/open62541pp/services/NodeManagement.h, include/open62541pp/services/services.h, src/ServerContext.h, src/services/Method.cpp, src/services/NodeManagement.cpp, src/types/Composed.cpp, tests/Node.cpp, tests/Services.cpp
=> feat: methods

examples/client_subscription.cpp, examples/server_instantiation.cpp, include/open62541pp/Common.h, include/open62541pp/services/Attribute.h, src/Client.cpp, src/ClientContext.h, tests/Client.cpp, tests/TypeWrapper.cpp
=> chore: fix typos

include/open62541pp/types/Builtin.h, src/types/Builtin.cpp, tests/Types.cpp
As preparation for `UA_DataSource` implementation.
=> feat: add NumericRange type

README.md, examples/server.cpp, examples/server_instantiation.cpp, examples/server_minimal.cpp, examples/server_valuecallback.cpp, include/open62541pp/Node.h
Fluent interface for `Node` write/setter methods. As discussed in #59.
=> feat: fluent node interface

doc/example.dox, examples/CMakeLists.txt, examples/server_datasource.cpp, include/open62541pp/ErrorHandling.h, include/open62541pp/Server.h, include/open62541pp/ValueBackend.h, include/open62541pp/types/Builtin.h, src/Client.cpp, src/Server.cpp, src/ServerContext.h, src/services/MonitoredItem.cpp, src/services/NodeManagement.cpp, src/services/Subscription.cpp, src/types/Builtin.cpp, tests/Server.cpp, tests/Types.cpp
Implement functionality of `UA_Server_setVariableNode_dataSource`.
Data sources can be added with following `Server` method:
```cpp
void Server::setVariableNodeValueBackend(const NodeId& id, ValueBackendDataSource backend);
```
=> feat: value data source

include/open62541pp/services/View.h, src/services/View.cpp, tests/Services.cpp
=> feat: services::browseRecursive

include/open62541pp/Node.h, src/Node.cpp, tests/Node.cpp
Helper methods to read/write object properties.
=> feat: add `Node::readObjectProperty`, `Node::writeObjectProperty`

include/open62541pp/Node.h, include/open62541pp/services/NodeManagement.h, src/services/NodeManagement.cpp, tests/Node.cpp, tests/Services.cpp
Add missing function / `Node` method to delete a reference.
=> feat: add `services::deleteReference`, `Node::deleteReference`

doc/example.dox, examples/CMakeLists.txt, examples/events/client_eventfilter.cpp, include/open62541pp/Subscription.h, include/open62541pp/services/MonitoredItem.h, include/open62541pp/types/Composed.h, src/Subscription.cpp, src/services/MonitoredItem.cpp, src/types/Composed.cpp, tests/Services.cpp, tests/Subscription_MonitoredItem.cpp, tests/Types.cpp
- Add filter wrapper types:
- `ContentFilterElement`
- `ContentFilter`
- `DataChangeFilter`
- `EventFilter`
- `AggregateFilter`
- Example how to filter events client-side
=> feat: filter

include/open62541pp/services/Attribute.h, include/open62541pp/types/Builtin.h, include/open62541pp/types/Composed.h, src/Node.cpp, src/services/Attribute.cpp, src/types/Builtin.cpp, src/types/Composed.cpp, tests/Types.cpp
=> feat: bundle multiple read/write requests

.github/workflows/open62541-compatibility.yml, CMakeLists.txt
Update submodule to latest open62541 version v1.3.7.
=> feat: update open62541 to v1.3.7

include/open62541pp/Node.h, include/open62541pp/services/NodeManagement.h, src/services/NodeManagement.cpp
=> fix: return output node id

src/services/NodeManagement.cpp, tests/Services.cpp
=> test: return output node, random node id

include/open62541pp/services/NodeManagement.h, include/open62541pp/services/View.h, include/open62541pp/types/Composed.h, src/services/NodeManagement.cpp, src/types/Composed.cpp, tests/Types.cpp
Expose raw node management services (client only):
- `services::addNodes`
- `services::addReferences`
- `services::deleteNodes`
- `services::deleteReferences`
=> feat: raw NodeManagement services

src/CustomLogger.cpp, src/CustomLogger.h, tests/Logger.cpp
=> fix: setLogger memory leak

README.md
=> chore: add project status and v1.0.0 milestone in readme

include/open62541pp/TypeConverter.h, include/open62541pp/TypeWrapper.h, include/open62541pp/detail/helper.h, include/open62541pp/types/NodeId.h, src/detail/helper.cpp, src/services/Method.cpp, src/services/NodeManagement.cpp, src/services/View.cpp, src/types/Builtin.cpp, src/types/Composed.cpp, src/types/ExtensionObject.cpp, src/types/NodeId.cpp, src/types/Variant.cpp, tests/TypeConverter.cpp, tests/Types.cpp, tests/helper.cpp
Add helper functions for safer (and faster) generic type handling.
=> refactor: generic type handling

README.md
=> docs: mention supported open62541 versions and CI pipeline

examples/client_find_servers.cpp, include/open62541pp/Client.h, include/open62541pp/Server.h, src/CustomLogger.cpp, src/Server.cpp, tests/Logger.cpp, tests/Server.cpp, tests/helper/Runner.h
=> feat: constructor for Server which takes a logger

include/open62541pp/Common.h, include/open62541pp/NodeIds.h, include/open62541pp/types/Composed.h, tools/gen_nodeids.py
See https://reference.opcfoundation.org/Core/Part6/v105/docs/5.2.4
=> fix: underlying type of enumerations must be int32

include/open62541pp/ErrorHandling.h, include/open62541pp/detail/helper.h, include/open62541pp/types/Builtin.h, src/Client.cpp, src/Crypto.cpp, src/Event.cpp, src/Server.cpp, src/Session.cpp, src/services/Attribute.cpp, src/services/Method.cpp, src/services/MonitoredItem.cpp, src/services/NodeManagement.cpp, src/services/Subscription.cpp, src/services/View.cpp, src/types/Builtin.cpp, src/types/ExtensionObject.cpp
Heavily used internally. Previously named `detail::throwOnBadStatus`.
=> feat: make throwIfBad function public

README.md
=> docs: fix find_package command for pre-compiled library integration

include/open62541pp/Node.h, src/Node.cpp
In preparation for compile-time `NodeClass` checks.
=> refactor: implicit Node instantiation, inline methods

examples/client_browse.cpp, include/open62541pp/Common.h
Avoid `string_view` dependency in `Common.h` header
=> feat!: remove getNodeClassName from Common.h

include/open62541pp/types/DataValue.h, include/open62541pp/types/Variant.h, src/Event.cpp, tests/Services.cpp
=> feat: variant policy for Variant::fromScalar, Variant::fromArray

README.md
How to integrate open62541pp with vcpkg.
=> docs: vcpkg

examples/client_subscription.cpp
=> fix: error handling in client_subscription example

.github/workflows/examples.yml, tools/run_examples.py
Run server/client examples as part of the CI workflows.
=> ci: run examples

include/open62541pp/services/Method.h, src/services/Method.cpp, tests/Services.cpp
Raw call service to call one or more server methods with a single request:
```cpp
CallResponse call(Client& client, const CallRequest& request);
template <typename CompletionToken = DefaultCompletionToken>
auto callAsync(Client& client, const CallRequest& request, CompletionToken&& token = DefaultCompletionToken());
```
=> feat: raw call service

include/open62541pp/AccessControl.h, include/open62541pp/Client.h, include/open62541pp/Common.h, include/open62541pp/DataType.h, include/open62541pp/MonitoredItem.h, include/open62541pp/Node.h, include/open62541pp/Subscription.h, include/open62541pp/TypeRegistry.h, include/open62541pp/TypeWrapper.h, include/open62541pp/detail/helper.h, include/open62541pp/services/Attribute.h, include/open62541pp/services/MonitoredItem.h, include/open62541pp/services/detail/RequestHandling.h, include/open62541pp/types/Composed.h, include/open62541pp/types/Variant.h, src/services/MonitoredItem.cpp, tests/TypeWrapper.cpp, tests/Types.cpp
Avoid open62541 dependency in `Common.h`.
=> refactor: avoid open62541 dependency in `Common.h`

include/open62541pp/Common.h, include/open62541pp/Server.h, include/open62541pp/types/Builtin.h, include/open62541pp/types/NodeId.h, src/Server.cpp, src/types/Builtin.cpp, src/types/NodeId.cpp
Add `NamespaceIndex` alias for `uint16_t`.
=> feat: NamespaceIndex alias for uint16_t

.github/workflows/ci.yml, CMakeLists.txt, src/Crypto.cpp
Single test with cross-platform test matrix.
Wrong coverage #191 is fixed with `disable_search` parameter in [codecov-action](https://github.com/codecov/codecov-action/tree/v4.1.0?tab=readme-ov-file#arguments).
=> ci: unify test matrix

include/open62541pp/types/ExtensionObject.h, include/open62541pp/types/Variant.h
Fix for bug described in #251.
=> fix: compare UA_DataType by typeId, not addresses

doc/Doxyfile.in, include/open62541pp/services/Attribute.h, include/open62541pp/services/Attribute_highlevel.h, include/open62541pp/services/Method.h, include/open62541pp/services/NodeManagement.h, include/open62541pp/services/View.h, tools/gen_attribute_highlevel.py
- Add default completion token for high-level attribute write functions
- Update docs of completion tokens
=> fix: default completion token for highlevel attribute write functions

doc/Doxyfile.in, include/open62541pp/Bitmask.h, include/open62541pp/Event.h, include/open62541pp/MonitoredItem.h, include/open62541pp/Node.h, include/open62541pp/Server.h, include/open62541pp/Session.h, include/open62541pp/Subscription.h, include/open62541pp/TypeWrapper.h, include/open62541pp/services/Attribute.h, include/open62541pp/services/Attribute_highlevel.h, include/open62541pp/services/Method.h, include/open62541pp/services/MonitoredItem.h, include/open62541pp/services/NodeManagement.h, include/open62541pp/services/Subscription.h, include/open62541pp/services/View.h, include/open62541pp/types/DataValue.h, include/open62541pp/types/NodeId.h, include/open62541pp/types/Variant.h, tools/gen_attribute_highlevel.py
- Add missing `@defgroup` titles
- Add missing `@param` descriptions
- Document deprecated features
=> docs: add missing descriptions, fix warnings

.github/workflows/open62541-compatibility.yml, CMakeLists.txt
Update to the latest patch release `v1.3.10` before updating to `v1.4`.
=> feat: update open62541 to v1.3.10

examples/server_datasource.cpp
=> fix: trigger value change in server_datasource example

include/open62541pp/types/Composed.h
=> fix: linking shared library windows

include/open62541pp/Bitmask.h, include/open62541pp/Common.h, include/open62541pp/Event.h, include/open62541pp/MonitoredItem.h, include/open62541pp/Node.h, include/open62541pp/Session.h, include/open62541pp/Subscription.h, include/open62541pp/TypeConverter.h, include/open62541pp/TypeWrapper.h, include/open62541pp/types/DataValue.h, include/open62541pp/types/NodeId.h, include/open62541pp/types/Variant.h, tests/Bitmask.cpp
Clean up code and remove all deprecated functions / types.
=> feat!: remove all deprecations

include/open62541pp/services/Subscription.h, include/open62541pp/services/detail/RequestHandling.h, include/open62541pp/types/Composed.h, src/services/Subscription.cpp, tests/Types.cpp
New subscription service functions using raw requests/responses:
```cpp
CreateSubscriptionResponse createSubscription(
Client& connection,
const CreateSubscriptionRequest& request,
StatusChangeNotificationCallback statusChangeCallback = {},
DeleteSubscriptionCallback deleteCallback = {}
);
ModifySubscriptionResponse modifySubscription(
Client& connection, const ModifySubscriptionRequest& request
) noexcept;
SetPublishingModeResponse setPublishingMode(
Client& connection, const SetPublishingModeRequest& request
) noexcept;
DeleteSubscriptionsResponse deleteSubscriptions(
Client& connection, const DeleteSubscriptionsRequest& request
) noexcept;
```
=> feat: raw subscription service

include/open62541pp/Client.h, include/open62541pp/detail/ClientContext.h, src/Client.cpp, tests/Client.cpp, tests/helper/Runner.h
Add new member function to set inactivity callback: `Client::onInactive`
Closes #284
=> feat: client inactivity callback

.github/workflows/codegen.yml, tools/gen_attribute_highlevel.py, tools/gen_nodeids.py, tools/gen_typeregistry_native.py
Check if generated source files are up-to-date.
=> ci: codegen workflow

CMakeLists.txt, include/open62541pp/Config.h.in
Add version macros:
- `UAPP_VERSION`: version string like `0.14.0`
- `UAPP_VERSION_MAJOR`: int like `0`
- `UAPP_VERSION_MINOR`: int like `14`
- `UAPP_VERSION_PATCH`: int like `0`
=> feat: version macro

CHANGELOG.md, doc/Doxyfile.in, doc/error_handling.md, doc/overview.dox
=> docs: error handling

include/open62541pp/detail/client_context.hpp, include/open62541pp/detail/server_context.hpp, src/client.cpp, src/client_config.hpp, src/server.cpp, src/server_config.hpp, tests/client.cpp, tests/server.cpp
Implement `ServerConfig` and `ClientConfig` as wrapper types (`Wrapper<UA_ServerConfig>` and `Wrapper<UA_ClientConfig>`).
=> refactor: ServerConfig / ClientConfig as wrapper

.github/workflows/open62541-compatibility.yml, tests/plugin_create_certificate.cpp, tests/services_monitoreditem.cpp, tests/subscription_monitoreditem.cpp
Some bugs got fixed in v1.4.6, see #362.
=> ci: update to latest patch release of open62541 v1.4

include/open62541pp/services/attribute.hpp, include/open62541pp/services/detail/async_transform.hpp, include/open62541pp/services/detail/client_services.hpp, include/open62541pp/services/detail/request_handling.hpp, include/open62541pp/services/detail/response_handling.hpp, include/open62541pp/services/method.hpp, include/open62541pp/services/nodemanagement.hpp, include/open62541pp/services/view.hpp, src/services_attribute.cpp, src/services_method.cpp, src/services_monitoreditem.cpp, src/services_nodemanagement.cpp, src/services_view.cpp, tests/CMakeLists.txt, tests/async.cpp, tests/services_helper.cpp, tests/services_method.cpp
The special async token `TransformToken` simplifies the implementation of async function overloads that perform some transformation on the output data.
=> refactor: async TransformToken

include/open62541pp/detail/client_context.hpp, include/open62541pp/services/detail/async_hook.hpp, include/open62541pp/services/detail/async_transform.hpp, include/open62541pp/services/detail/request_handling.hpp, include/open62541pp/services/subscription.hpp, src/services_subscription.cpp, tests/services_helper.cpp, tests/services_subscription.cpp
Async support for subscription service set.
See #389.
=> feat: async subscription service set

include/open62541pp/services/detail/request_handling.hpp, include/open62541pp/services/detail/response_handling.hpp, include/open62541pp/services/monitoreditem.hpp, include/open62541pp/services/nodemanagement.hpp, include/open62541pp/services/subscription.hpp, src/services_monitoreditem.cpp, src/services_subscription.cpp, tests/services_helper.cpp, tests/services_monitoreditem.cpp
Async support for MonitoredItem service set.
Closes #389.
=> feat: async monitoreditem service set

include/open62541pp/typeregistry.hpp, include/open62541pp/typewrapper.hpp
Make TypeWrapper depend on TypeRegistry.
=> refactor: invert dependency of TypeWrapper and TypeRegistry

examples/CMakeLists.txt, include/open62541pp/services/detail/request_handling.hpp, include/open62541pp/services/detail/subscription_context.hpp, include/open62541pp/types_composed.hpp, src/client.cpp
Fix build with disabled options:
- `UA_ENABLE_DA`
- `UA_ENABLE_METHODCALLS`
- `UA_ENABLE_SUBSCRIPTIONS`
- `UA_ENABLE_SUBSCRIPTIONS_EVENTS`
=> fix: compile with minimal open62541 options

examples/method/client_method_async.cpp, include/open62541pp/node.hpp, tests/node.cpp
Add async `Node` functions (`Client` only).
=> feat: async Node functions

include/open62541pp/config.hpp.in, include/open62541pp/types_composed.hpp, tests/plugin_create_certificate.cpp, tests/types_composed.cpp
Add `DataAccess` wrapper types:
- `Range`
- `EUInformation`
- `AxisScaleEnumeration`
- `ComplexNumberType`
- `DoubleComplexNumberType`
- `AxisInformation`
- `XVType`
=> feat: add DataAccess wrapper types

examples/custom_datatypes/server_custom_datatypes.cpp, include/open62541pp/datatype.hpp, tests/datatype.cpp
Remove `get` prefix of `DataType` getters.
See #459.
=> feat!: remove get prefix of DataType getters

tests/plugin_create_certificate.cpp
Test encrypted client/server connection with custom application URIs.
The application URIs of both client and server match the `URI` parameter in `SubjectAltKey` of the X.509 certificate.
As discussed in #484.
=> test: use custom application URIs with certificate

examples/client_async.cpp, examples/client_subscription.cpp, examples/custom_datatypes/client_custom_datatypes.cpp, examples/events/client_eventfilter.cpp, examples/events/server_events.cpp, examples/method/client_method.cpp, examples/method/client_method_async.cpp, examples/method/server_method.cpp, examples/server_accesscontrol.cpp, examples/server_datasource.cpp, examples/server_valuecallback.cpp, examples/typeconversion.cpp, include/open62541pp/node.hpp, include/open62541pp/services/detail/attribute_handler.hpp, include/open62541pp/types.hpp, src/client.cpp, src/server.cpp, tests/client_service.cpp, tests/node.cpp, tests/server.cpp, tests/services_attribute.cpp, tests/services_method.cpp, tests/services_monitoreditem.cpp, tests/session.cpp, tests/types_builtin.cpp, tests/ua_types.cpp
Remove `get` prefix of `Variant` getters.
See #459.
=> feat!: remove get prefix of Variant getters

examples/typeconversion.cpp, include/open62541pp/typeconverter.hpp, include/open62541pp/types.hpp, tests/typeconverter.cpp
Add and use two helper functions:
- `detail::fromNative`
- `detail::toNative`
=> refactor: TypeConverter helper functions fromNative, toNative

examples/server_valuecallback.cpp, include/open62541pp/plugin/nodestore.hpp, src/server.cpp, tests/server.cpp
=> feat!: add node id parameter to ValueCallback functions

CMakeLists.txt, examples/server_valuecallback.cpp, include/open62541pp/detail/open62541/common.h, include/open62541pp/detail/server_context.hpp, include/open62541pp/plugin/nodestore.hpp, include/open62541pp/server.hpp, src/plugin/nodestore.cpp, src/server.cpp, tests/server.cpp
=> feat!: ValueCallback as abstract base class (ValueCallbackBase)

examples/server_datasource.cpp, include/open62541pp/detail/server_context.hpp, include/open62541pp/plugin/nodestore.hpp, include/open62541pp/server.hpp, src/plugin/nodestore.cpp, src/server.cpp, tests/server.cpp
=> feat!: DataSource as abstract base class (DataSourceBase)

CHANGELOG.md, include/open62541pp/detail/server_context.hpp, include/open62541pp/session.hpp, src/plugin/accesscontrol.cpp, src/plugin/nodestore.cpp, src/server.cpp, tests/plugin_accesscontrol.cpp, tests/session.cpp
Access session context with `Session::context()`.
=> feat: expose session context in Session class

include/open62541pp/types.hpp
=> fix: unreachable code in NodeId::identifierIf

include/open62541pp/services/attribute.hpp, tests/services_attribute.cpp
=> fix: deallocation failure in read/write requests

include/open62541pp/detail/traits.hpp, include/open62541pp/node.hpp, include/open62541pp/span.hpp, include/open62541pp/types.hpp, tests/node.cpp, tests/traits.cpp
=> fix: Node::writeValueArray for std::vector<bool>

src/server.cpp, tests/server.cpp
=> fix: check if server runs before calling UA_Server_run_shutdown

.github/workflows/ci.yml, .github/workflows/open62541-compatibility.yml, CMakePresets.json, include/open62541pp/detail/open62541/pop_options.h, include/open62541pp/detail/open62541/push_options.h
=> ci: enable multithreading support

include/open62541pp/client.hpp, include/open62541pp/plugin/log_default.hpp, include/open62541pp/server.hpp, include/open62541pp/types.hpp, src/client.cpp, src/server.cpp
Remove functions that have been deprecated at least since v0.15.0.
=> feat!: remove deprecations ≤ v0.15.0

include/open62541pp/types.hpp
Always use `std::chrono::system_clock` for conversions between `UA_DateTime` and `std::chrono::time_point`.
=> fix: avoid clock conversions with DateTime

include/open62541pp/types.hpp, tests/types_builtin.cpp
Allow `DateTime` dates before Unix time (1970).
=> fix: DateTime before 1970
